version: '3.9'

services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./test:/etc/nginx/ssl
      - ./dist:/usr/share/nginx/html
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf # to retain syntax highlighting
      - NGINX_SERVER_NAME=localhost
      - NGINX_SSL_CERT=/etc/nginx/ssl/localhost.crt
      - NGINX_SSL_KEY=/etc/nginx/ssl/localhost.key
  pocketbase:
    restart: always
    container_name: pocketbase
    build:
      context: .
      dockerfile: ./pocketbase/Dockerfile
    volumes:
      - pocketbase-volume:/app/data
      - ./pocketbase/pb_migrations:/app/data/pb_migrations
    ports:
      - "8090:8090"

volumes:
  pocketbase-volume:
    name: pocketbase-volume
