version: '3.9'

services:
  nginx:
    restart: always
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
      - "80:80"
      - "443:443"
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf # to retain syntax highlighting
      - NGINX_SERVER_NAME=localhost
      - NGINX_SSL_CERT=/etc/nginx/ssl/localhost.crt
      - NGINX_SSL_KEY=/etc/nginx/ssl/localhost.key
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./test/dummy_ssl:/etc/nginx/ssl
      # - ./dist:/usr/share/nginx/html # to update frontend with `pnpm run build` without having to rebuild nginx container

  pocketbase:
    restart: always
    container_name: pocketbase
    build:
      context: .
      dockerfile: ./pocketbase/Dockerfile
    # ports:
    #   - "8090:8090" # for direct access without nginx
    volumes:
      - pb_data_volume:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations

volumes:
  pb_data_volume:
    name: pb_data
